cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'caskroom/drivers'
tap 'homebrew/versions'
tap 'neovim/neovim'
tap 'tjanson/firefox-esr'

brew 'ack'
brew 'aspell'
brew 'axel'
brew 'certbot'
brew 'cheat'
brew 'colordiff'
brew 'cowsay'
brew 'elixir'
brew 'erlang', args: ["--without-wxmac"]
brew 'fish'
brew 'fswatch'
brew 'geckodriver'
brew 'git-lfs'
brew 'go', args: [ "--devel" ] # Make hub work
brew 'graphviz'
brew 'heroku'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'libxml2'
brew 'libxslt'
brew 'neovim'
brew 'node'
brew 'phantomjs'
brew 'postgresql94'
`brew link --force postgresql94`
brew 'python3'
brew 'qt'
brew 'rabbitmq'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'terminal-notifier'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'git'

cask '1password'
cask 'alfred'
cask 'anaconda'
cask 'backblaze'
cask 'bartender'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'elm-platform'
cask 'firefox-esr45'
cask 'fluid'
cask 'flux'
cask 'focus'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'google-drive'
cask 'grandperspective'
cask 'iTerm2'
cask 'intellij-idea-ce'
cask 'istat-menus'
cask 'java'
cask 'licecap'
cask 'logitech-gaming-software'
cask 'mattr-slate'
cask 'omnifocus'
cask 'pocketcasts'
cask 'resilio-sync'
cask 'screenhero'
cask 'selfcontrol'
cask 'skim'
cask 'spotify'
cask 'toggldesktop'
cask 'postman'
cask 'keybase'
cask 'soapui'

mas 'Airmail 3', id: 918858936
mas 'Annotate', id: 918207447
mas 'Marked 2', id: 890031187
mas 'Pocket', id: 568494494
mas 'Slack', id: 803453959
mas 'Due — Reminders, Countdown Timers', id: 524373870
