#!/usr/bin/env ruby

LINE_REGEX = /^  \* (\S+) \(.*$/

def outdated_gems
  `bundle outdated`
    .split("\n")
    .map {|line| gem_name(line) }
    .compact
end

def gem_name(line)
  if line =~ LINE_REGEX
    line.match(LINE_REGEX)[1]
  else
    nil
  end
end

def main
  outdated_gems.each_with_index do |gem, index|
    puts "[#{index+1}/#{outdated_gems.count}]: #{gem}"
    puts `bundle update #{gem}`
    `git commit -a -m "Updated #{gem}"`
  end
end

if __FILE__ == $0
  main
end
