#!/usr/bin/env ruby
require 'trello'

def complain(message)
  puts message
  exit 1
end

if __FILE__ == $0
  if ARGV.size == 1
    board_name = ARGV.first
    api_key = ENV['TRELLO_API_KEY']
    complain "Please set TRELLO_API_KEY" unless api_key
    member_token = ENV['TRELLO_MEMBER_TOKEN']
    complain "Please set TRELLO_MEMBER_TOKEN" unless member_token

    Trello.configure do |config|
      config.developer_public_key = api_key
      config.member_token = member_token
    end

    board = Trello::Board.all.detect { |board| board.name == board_name }
    complain "Could not find board '#{board_name}'" unless board

    board.lists.each do |list|
      puts "  * #{list.name} (#{list.cards.size})"
      list.cards.each do |card|
        puts "    * #{card.name}"
      end
    end
  else
    complain "Usage: #{$0} BOARD_NAME"
  end
end
